name: Prepublish for release test
on:
  workflow_dispatch:
jobs:
  prerelease:
    runs-on: ubuntu-latest
    environment:
        name: dev
        url: https://www.npmjs.com/package/junit2json
    permissions:
      contents: write
      id-token: write
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: .tool-versions
          registry-url: 'https://registry.npmjs.org'

      # Ensure npm 11.5.1 or later for trusted publishing
      - name: Update npm
        run: npm install -g npm@latest

      - name: Setup git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      # npm publish and push updated package.json
      - name: prepublish to npm and jsr
        run: |
          npm run release:prepublish
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
