name: Prepublish for release test
on:
  workflow_dispatch:
jobs:
  prerelease:
    runs-on: ubuntu-latest
    environment:
        name: dev
        url: https://www.npmjs.com/package/junit2json
    permissions:
      contents: write
      id-token: write
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.18.0'
          registry-url: 'https://registry.npmjs.org'
      - uses: earthly/actions-setup@v1.0.13
        with:
          version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      # npm publish and push updated package.json
      - name: prepublish to npm and jsr
        run: |
          npm run release:prepublish
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
